target 'Pesto' do
  pod 'MaterialComponents/AnimationTiming', :path => '../../'
  pod 'MaterialComponents/AppBar', :path => '../../'
  pod 'MaterialComponents/Collections', :path => '../../'
  pod 'MaterialComponents/FlexibleHeader', :path => '../../'
  pod 'MaterialComponents/Ink', :path => '../../'
  pod 'MaterialComponents/ShadowElevations', :path => '../../'
  pod 'MaterialComponents/ShadowLayer', :path => '../../'
  pod 'MaterialComponents/Typography', :path => '../../'

end

