target 'Pesto' do
  pod 'MaterialComponents/AnimationTiming'
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/FlexibleHeader'
  pod 'MaterialComponents/Ink'
  pod 'MaterialComponents/ShadowElevations'
  pod 'MaterialComponents/ShadowLayer'
  pod 'MaterialComponents/Typography'
  
end

