# Doc site configuration.
# TODO(shyndman): Link to documentation.
basepath: /ios
site_platform: ios
site_title: Material Components for iOS
site_short_title: iOS
site_description: >
  Material Components for iOS is a set of user interface components that help iOS app developers build apps with material design.
repo_url: https://github.com/material-components/material-components-ios/
repo_stable_branch: stable
