disabled_rules:
  - closure_parameter_position
  - colon
  - control_statement # Enable eventually
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - legacy_constructor # Enable eventually
  - line_length
  - statement_position
  - syntactic_sugar
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter

variable_name: warning
