# Copyright 2017-present The Material Components for iOS Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

http_archive(
    name = "build_bazel_rules_apple",
    url = "https://github.com/bazelbuild/rules_apple/archive/0.3.0.zip",
    strip_prefix = "rules_apple-0.3.0",
    # Generated by running: openssl sha -sha256 <path to zip>
    sha256 = "0c2f7b903c2334a3e7e0b565f0f80a854047ac36202978318f853cb762bf33f3"
)

git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "0.2.0",
)

http_file(
    name = "xctestrunner",
    executable = 1,
    url = "https://github.com/google/xctestrunner/releases/download/0.2.1/ios_test_runner.par",
)

git_repository(
    name = "bazel_ios_warnings",
    remote = "https://github.com/material-foundation/bazel_ios_warnings.git",
    tag = "v2.0.0",
)

git_repository(
    name = "material_internationalization_ios",
    remote = "https://github.com/material-foundation/material-internationalization-ios.git",
    tag = "v1.0.4",
)

git_repository(
    name = "material_text_accessibility_ios",
    remote = "https://github.com/material-foundation/material-text-accessibility-ios.git",
    commit = "fd570d71ae0124c75ad5af00e6b8b4b1668d5e40",
)

git_repository(
    name = "motion_interchange_objc",
    remote = "https://github.com/material-motion/motion-interchange-objc.git",
    tag = "v1.4.0",
)

git_repository(
    name = "motion_animator_objc",
    remote = "https://github.com/material-motion/motion-animator-objc.git",
    tag = "v2.5.0",
)

git_repository(
    name = "motion_transitioning_objc",
    remote = "https://github.com/material-motion/motion-transitioning-objc.git",
    tag = "v5.0.0",
)
