#!/bin/bash
#
# Copyright 2016-present Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Writes a list of modified component sources for the latest release to stdout.

if [ ! $(git rev-parse --verify release-candidate 2> /dev/null) ]; then
  echo "Please cut a release first by running scripts/release/cut."
  exit 1
fi

git diff --name-status --diff-filter=ADR origin/master..release-candidate \
  | grep "components/" \
  | grep "src/"
