#!/bin/bash
#
# Copyright 2016-present Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Returns a version number bumped from the latest release on origin/master.

usage() {
  echo $"Usage: $0 {major|minor|patch}"
  exit 1
}

LATEST_VERSION=$(git describe --abbrev=0 --tags origin/master | cut -dv -f2)
parts=( ${LATEST_VERSION//./ } )

case "$1" in
  major)
    ((parts[0]++))
    ;;

  minor)
    ((parts[1]++))
    ;;

  patch)
    ((parts[2]++))
    ;;

  *)
    usage
esac

echo "${parts[0]}.${parts[1]}.${parts[2]}"
