// Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#import <UIKit/UIKit.h>

#import "MaterialIcons.h"

// This file was automatically generated by running ./scripts/sync_icons.sh
// Do not modify directly.

@interface MDCIcons (ic_reorder)

/*
 Returns the image for the ic_reorder image contained in
 MaterialIcons_ic_reorder.bundle.
 */
+ (nullable UIImage *)imageFor_ic_reorder;

@end
