// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/AppBar/src/MaterialAppBar.bundle/Resources/en.lproj/MaterialAppBar.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialAppBarStringTable[] = {
  @"MaterialAppBarBackButtonAccessibilityLabel",   // Back
};
#define kNumMaterialAppBarStrings 1
#define kMaterialAppBarStringsOffset 0
#define kMaterialAppBarStringsEnd 10000
static NSString *const kMaterialAppBarStringsTableName = @"MaterialAppBar";
