// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/AppBar/src/MaterialAppBar.bundle/Resources/en.lproj/MaterialAppBar.strings
// GENERATED BY: generate_string_tables.py

typedef enum {
  kStr_MaterialAppBarBackButtonAccessibilityLabel = 0,
} MaterialAppBarStringId;
