// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/FeatureHighlight/src/MaterialFeatureHighlight.bundle/Resources/en.lproj/MaterialFeatureHighlight.strings
// GENERATED BY: //depot/google3/googlemac/iPhone/Shared/Tools/generate_string_tables.py

typedef enum {
  kStr_MaterialFeatureHighlightDismissAccessibilityHint = 0,
} MaterialFeatureHighlightStringId;
