// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/FeatureHighlight/src/MaterialFeatureHighlight.bundle/Resources/en.lproj/MaterialFeatureHighlight.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialFeatureHighlightStringTable[] = {
    @"MaterialFeatureHighlightDismissAccessibilityHint",  // Double-tap to dismiss.
};
#define kNumMaterialFeatureHighlightStrings 1
#define kMaterialFeatureHighlightStringsOffset 0
#define kMaterialFeatureHighlightStringsEnd 10000
static NSString *const kMaterialFeatureHighlightStringsTableName = @"MaterialFeatureHighlight";
