#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates a log from the last release to the current one.
#
# Examples:
#
# Summarized list of changes for the FlexibleHeader component.
#    release/log --pretty=oneline components/FlexibleHeader/src/
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"; pushd $DIR >> /dev/null
ROOT="$(git rev-parse --show-toplevel | tail -n1)"; popd >> /dev/null
cd $ROOT >> /dev/null

if [ ! $(git rev-parse --verify release-candidate 2> /dev/null) ]; then
  echo "Please cut a release first by running scripts/release/cut."
  exit 1
fi

git --no-pager log origin/stable..release-candidate "$@"
