---
title:  "Slider"
layout: detail
section: components
excerpt: "The Slider component provides a material design control for selecting a value from a continuous range or discrete set of values."
---
