workspace 'MDCCatalog.xcworkspace'
project 'MDCCatalog.xcodeproj'

target "MDCCatalog" do
  project 'MDCCatalog.xcodeproj'
  pod 'MaterialComponentsCatalog', :path => '../'
  pod 'MaterialComponents', :path => '../'

  use_frameworks!
end

target "MDCUnitTests" do
  project 'MDCUnitTests.xcodeproj'
  pod 'MaterialComponentsUnitTests', :path => '../'
  pod 'MaterialComponents', :path => '../'

  use_frameworks!
end

post_install do |installer|
  pod_dir = File.dirname(installer.pods_project.path)

  mdc_xcconfigs = [
    "#{pod_dir}/Target Support Files/MaterialComponents/MaterialComponents.xcconfig",
  ]

  mdc_xcconfigs.each do |mdc_xcconfig|
    new_xcconfig = File.read(mdc_xcconfig)
    new_xcconfig << "\n#include \"../MaterialComponentsWarnings.xcconfig\""
    File.write(mdc_xcconfig, new_xcconfig)
  end
end
