#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly SCRIPTS_DIR="$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)"
readonly ROOT_DIR="$SCRIPTS_DIR/.."

# For the moment, we only have workspaces from CocoaPods projects.
readonly PODFILE_DIRS=$("$SCRIPTS_DIR"/manage_pods.py --dir "$ROOT_DIR" list)

workspaces=""
for i in ${PODFILE_DIRS}; do
  workspaces="$workspaces $(find "$i" -d 1 -name '*.xcworkspace')"
done

# For Catalog, we want the schemes named MDC*. For everything else, assume we
# only want the scheme with the same name as the workspace. This isn't totally
# future-proof and is a reasonable tradeoff for now.
for workspace in $workspaces; do
  if [[ $workspace == */MDCCatalog.xcworkspace ]]; then
    schemes=$("$SCRIPTS_DIR"/xcode/list_xcode_workspace schemes "$workspace") 
    for scheme in $schemes; do
      if [[ $scheme == MDC* ]]; then
        echo "$workspace":"$scheme"
      fi
    done
  else
    name=$("$SCRIPTS_DIR"/xcode/list_xcode_workspace name "$workspace")
    echo "$workspace":"$name"
  fi
done
