# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BuildingBeautifulApps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShrineCodelabObjc
  pod 'MaterialComponents'
end
