# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZShadow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'MaterialComponents/ShadowElevations', :path => '../../'
  pod 'MaterialComponents/ShadowLayer', :path => '../../'
end
