#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly COMPONENT_DIR=$1

readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR=$(dirname $(dirname "$SCRIPTS_DIR"))
readonly EXAMPLES_DIR=$COMPONENT_DIR/examples

# Private components do not require examples.
if [[ $COMPONENT_DIR != *"/private/"* ]]; then
  if [ ! -d $EXAMPLES_DIR ]; then
    echo "Error: '$COMPONENT_DIR' is missing an 'examples' directory."
    exit -1
  fi

  # Check source files for Swift examples.
  readonly FILES=$(find "$EXAMPLES_DIR" -name '*.swift')
  if [[ -z "$FILES" ]]; then
    echo "Error: '$EXAMPLES_DIR' has no Swift examples."
    exit -1
  fi
fi
