#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly COMPONENT_DIR=$1

readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR=$(dirname $(dirname "$SCRIPTS_DIR"))
readonly NAV_YAML="$ROOT_DIR/site-source/jekyll-site-src/_data/navigation.yaml"

if [ ! -f $NAV_YAML ]; then
  echo "Error: Could not find the left nav configuration at '$NAV_YAML'."
  echo "Please run scripts/build_site.sh once to install the site sources."
  exit -1
fi

readonly COMPONENT_NAME=$(basename $COMPONENT_DIR)

# Private components should not exist in the left nav.
if [[ "$COMPONENT_DIR" == *"private/"* ]]; then
  should_exist=0
else
  should_exist=1
fi

# Search for an entry like "- name: ComponentName", which is the list entry for the
# component in the left nav.
GREP_OPTIONS="--quiet"
grep $GREP_OPTIONS -- "- name: $COMPONENT_NAME" $NAV_YAML
if [[ "$?" -eq 0 ]]; then 
  found=1
else
  found=0
fi

if [[ $should_exist -eq 1 ]]; then
  if [[ $found -eq 0 ]]; then
    echo "Error: $COMPONENT_NAME not found in left nav config '$NAV_YAML'."
    exit -1
  fi
else
  if [[ $found -eq 1 ]]; then
    echo "Error: Private component $COMPONENT_NAME found in left nav config '$NAV_YAML'."
    exit -1
  fi
fi 
