#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly COMPONENT_DIR=$1

readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR=$(dirname $(dirname "$SCRIPTS_DIR"))

# Check source files.
readonly FILES=$(find "$COMPONENT_DIR" -name '*.m' -or -name '*.h' -or -name '*.swift')
readonly PATTERN="Copyright [^ ]+ the Material Components for iOS authors. All Rights Reserved."

failure_count=0
for file in $FILES; do 
  grep --extended-regexp --quiet "$PATTERN" $file
  if [[ "$?" -ne 0 ]]; then
    echo "Error: $file is missing the license stanza."
    failure_count=$((failure_count+1))     
  fi
done

if [[ $failure_count -ne 0 ]]; then
  exit -1
fi
