#!/usr/bin/php
<?php
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exec("find components -name 'README.md'", $output);
foreach ($output as $file) {
  $contents = file_get_contents($file);

  if (preg_match_all('/<\!--<div class="material-code-render" markdown="1">-->(.+?)<\!--<\/div>-->/sm',
                     $contents, $matches, PREG_OFFSET_CAPTURE)) {
    foreach ($matches[1] as $match) {
      $passes = false;
      if (preg_match_all('/~~~ objc(.+?)~~~.+?~~~ swift(.+?)~~~/sm', $match[0], $languages)) {
        $objc = trim($languages[1][0]);
        $swift = trim($languages[2][0]);
        if (!empty($objc) && !empty($swift)) {
          $passes = true;
        }
      }
      if (!$passes) {
        list($before) = str_split($contents, $match[1]);
        $line_number = strlen($before) - strlen(str_replace("\n", "", $before)) + 1;
        echo "$file:$line_number\n";
      }
    }
  }
}
