/*
 Copyright 2017-present the Material Components for iOS authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM: components/Snackbar/src/MaterialSnackbar.bundle/Resources/en.lproj/MaterialSnackbar.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialSnackbarStringTable[] = {
  @"MaterialSnackbarMessageViewTitleA11yHint",   // Double-tap to dismiss
};
#define kNumMaterialSnackbarStrings 1
#define kMaterialSnackbarStringsOffset 0
#define kMaterialSnackbarStringsEnd 10000
static NSString *const kMaterialSnackbarStringsTableName = @"MaterialSnackbar";
