// clang-format off
// NOLINTBEGIN

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM: components/ProgressView/src/MaterialProgressView.bundle/Resources/en.lproj/MaterialProgressView.strings
// GENERATED BY: //depot/google3/googlemac/iPhone/Shared/Tools/generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialProgressViewStringTable[] = {
  @"MaterialProgressViewAccessibilityLabel",   // Progress View
};
#define kNumMaterialProgressViewStrings 1
#define kMaterialProgressViewStringsOffset 0
#define kMaterialProgressViewStringsEnd 10000
static NSString *const kMaterialProgressViewStringsTableName = @"MaterialProgressView";

// NOLINTEND
// clang-format on
