// clang-format off
// NOLINTBEGIN

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM: components/ProgressView/src/MaterialProgressView.bundle/Resources/en.lproj/MaterialProgressView.strings
// GENERATED BY: //depot/google3/googlemac/iPhone/Shared/Tools/generate_string_tables.py

typedef enum {
  kStr_MaterialProgressViewAccessibilityLabel = 0,
} MaterialProgressViewStringId;

// NOLINTEND
// clang-format on
