---
title:  "Sprited Animation View"
layout: detail
section: components
excerpt: "The Sprited Animation View component provides an alternative to animating an array of images with an UIImageView."
---
