#!/bin/bash
#
# Copyright 2016-present Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit

build_log=build_log.txt
find * -name 'Podfile' | while read path; do
  project_dir=$(dirname $path)
  echo "Building in $project_dir..."
  pushd $(dirname $path) >/dev/null

  rm -rf Pods
  pod install --silent

  workspace=$(find . -d 1 -name '*.xcworkspace')
  scheme=$(xcodebuild build -workspace $workspace -list | grep "Information about workspace" | cut -d'"' -f2)
  xcodebuild clean -workspace $workspace -scheme $scheme >/dev/null
  
  if ! xcodebuild build -workspace $workspace -scheme $scheme >$build_log 2>&1; then
    echo "Failed to build $scheme in $workspace, log left in $project_dir/$build_log."
    echo "Continuing with next project..."
  else
    rm $build_log
    echo "Done."
  fi

  popd >/dev/null
done
