#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly BUILD_LOG=build_log.txt

# Build a list of workspaces to build.
# For now, we just have CocoaPods projects to worry about.
readonly PODFILE_DIRS=$("$SCRIPTS_DIR"/release/manage_pods.py list)


for i in $PODFILE_DIRS; do
  echo "Building in $i..."
  pushd $i >/dev/null

  workspace=$(find . -d 1 -name '*.xcworkspace')
  scheme=$(xcodebuild build -workspace $workspace -list | grep "Information about workspace" | cut -d'"' -f2)
  
  if ! xcodebuild build -workspace $workspace -scheme $scheme >$BUILD_LOG 2>&1; then
    echo "Failed to build $scheme in $workspace, log left in $i/$BUILD_LOG."
    echo "Continuing with next project..."
  else
    rm $BUILD_LOG
    echo "Done."
  fi

  popd >/dev/null
done
