#!/bin/bash -e
#
# Copyright 2019-present The Material Components for iOS Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a utility script that expands inline references in readme files. It is used by
# other scripts, like generate_readme and combine_readme.
#
# Args: $1 - tempoaray output path
#       $2 - topic doc path
#       $3 - expanded topic path
#       $4 - a relative doc path - relative to the topic doc path (optional)
#       $5 - component name (optional)
#
# Usage Examples: 
#   expand_inline_references tmp/releasing.out contributing/releasing.md contributing/releasing_template.md
#
# Note: Make sure to setup whitespace trimming if needed (IFS='')
#
expand_inline_references() {

  tmp_output_path="$1"
  expanded_topic_path="$2"
  topic_doc_path="$3/$4"
  doc_path="$4"
  component_name="$5"

  if [[ -z "$4" ]]; then
    topic_doc_path="$3"
    doc_path=$topic_doc_path
  fi
  IFS='' # Don't trim whitespace from lines
  cat "$tmp_output_path" | while read line; do
    if [[ $(echo $line | grep -e "^- \[.*\]\(.*\)$") ]]; then
      file=$(echo $line | cut -d'(' -f2 | cut -d')' -f1)
      file_path="$topic_doc_path/$file"
      echo "<!-- Extracted from $doc_path/$file -->" >> "$expanded_topic_path"
      echo >> "$expanded_topic_path"
      if [[ -z "$component_name" ]]; then
        cat "$file_path" >> "$expanded_topic_path"
       else
        cat "$file_path" | sed "s/<#ComponentName#>/$component_name/" >> "$expanded_topic_path"
       fi
      echo >> "$expanded_topic_path" # Ensure that there is always a newline between files.
    else
      echo "$line" >> "$expanded_topic_path"
    fi
  done
}