#!/bin/bash
#
# Copyright 2016-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Print a list of directories that contain our Xcode projects.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=$(dirname ${SCRIPT_DIR})
DIRS_TO_SEARCH="${ROOT_DIR}/catalog ${ROOT_DIR}/demos"

# So far, each of our Xcode projects is using CocoaPods, but this could change in the future.
for i in ${DIRS_TO_SEARCH}; do 
  ${SCRIPT_DIR}/release/manage_pods.py --dir "$i" list
done
#find ${DIRS_TO_SEARCH} -name Podfile -print0 | xargs -0 -n1 dirname | xargs
