#!/bin/bash
#
# Copyright 2017-present the Material Components for iOS authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR="$SCRIPTS_DIR/.."
readonly VERSION_NAME="VERSION"

if [ ! -f "$ROOT_DIR/$VERSION_NAME" ]; then
  >&2 echo "Missing \"$ROOT_DIR/$VERSION_NAME\", aborting."
  exit -1
fi

cat "$ROOT_DIR/$VERSION_NAME"
