// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/ActivityIndicator/src/MaterialActivityIndicator.bundle/Resources/en.lproj/MaterialActivityIndicator.strings
// GENERATED BY: generate_string_tables.py

typedef enum {
  kStr_MaterialActivityIndicatorInProgressAccessibilityLabel = 0,
  kStr_MaterialActivityIndicatorProgressHaltedAccessibilityLabel = 1,
  kStr_MaterialActivityIndicatorProgressCompletedAccessibilityLabel = 2,
} MaterialActivityIndicatorStringId;
