// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/ActivityIndicator/src/MaterialActivityIndicator.bundle/Resources/en.lproj/MaterialActivityIndicator.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialActivityIndicatorStringTable[] = {
  @"MaterialActivityIndicatorInProgressAccessibilityLabel",   // In Progress
  @"MaterialActivityIndicatorProgressHaltedAccessibilityLabel",   // Progress Halted
  @"MaterialActivityIndicatorProgressCompletedAccessibilityLabel",   // %ld Percent Complete
};
#define kNumMaterialActivityIndicatorStrings 3
#define kMaterialActivityIndicatorStringsOffset 0
#define kMaterialActivityIndicatorStringsEnd 10000
static NSString *const kMaterialActivityIndicatorStringsTableName = @"MaterialActivityIndicator";
