platform :ios, "8.0"
use_frameworks!

target 'Shrine' do
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/PageControl'
  pod 'RemoteImageServiceForMDCDemos', :path => '../supplemental'
end
